// components/ImageCard.vue
<template>
  <div class="image-card">
    <div :style="`background-image: url(/${img})`" class="content"></div>
    <div class="content">
      <h3>{{ title }}</h3>
      <p>{{ content }}</p>
      <a :href="link" target="_blank">リンク</a>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ImageCard',
  props: {
    img: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    content: {
      type: String,
      required: true,
    },
    link: {
      type: String,
      required: true,
    },
  },
};
</script>

<style lang="scss" scoped>
$radius-size: 10px;

.image-card {
  border-radius: $radius-size;
  border: 0.5px solid $text-black;
  height: 300px;
  margin: 10%;
  h2 {
    margin: 0;
  }
  img {
    height: 100%;
    width: 100%;
  }
  .content {
    height: 50%;
    border-radius: $radius-size $radius-size 0 0;
    background-size: cover;
    padding: 0 5%;
    h3 {
      text-align: center;
    }
  }
}
</style>

// src/components/ImageCard.svelte
<script lang='ts'>
	export let img: string = '';
	export let title: string = '';
	export let content: string = '';
	export let link: string = '';
</script>

<div class="card image-card">
	{#if img }
		<div
			style={`background-image: url(/${img})`}
			alt={`${img}`}
			class="card content div-img"
		></div>
	{:else}
		<div class="card content div-img no-picture">
			<p>NO PICTURE</p>
		</div>
	{/if}
	<div class="content">
		<h3>{ title }</h3>
		<p>{ content }</p>
		<a href={link} target="_blank" rel="noopener">You can show or get from here</a>
	</div>
</div>

<style lang="scss">
  $radius-size: 10px;

  .image-card {
    height: 400px;
    h2 {
      margin: 0;
    }
    img {
      height: 100%;
      width: 100%;
    }
    .content {
      border-radius: $radius-size;
      background-size: cover;
      padding: 0 5%;
      h3 {
        text-align: center;
      }
    }
    .div-img {
      height: 50%;
    }
  }

  .no-picture {
    align-items: center;
    display: flex;
    justify-content: center;
    background-color: $theme-black;
    p {
      font-weight: 700;
      font-size: 24px;
      color: $text-light;
    }
  }
</style>
