// components/ImageLink.vue
<template>
  <a :href="link" target="_blank">
    <img :src="src" width="64" height="64" />
  </a>
</template>

<script>
export default {
  name: 'ImageLink',
  props: {
    src: {
      type: String,
      required: true,
    },
    link: {
      type: String,
      required: true,
    },
  },
};
</script>

// src/components/ImageLink.svelte
<script lang="ts">
	export let src: string = '';
	export let link: string = '';
</script>
	<a href={link} target="_blank" class='card' rel="noopener">
		<img src={src} alt={link} width="32" height="32" />
	</a>
<style lang="scss">
  img {
    width: 64px;
    height: 64px;
    @media screen and (max-width: 1200px) {
      width: 32px;
      height: 32px;
    }
  }
</style>
